baseurl = "https://piotr-j.github.io/site/"
languageCode = "en-us"
title = "PiotrJ"
theme = "ghostwriter-clean"
pygmentsuseclasses = true
paginate = 9 # multiple of 3
copyright = "© 2015 Piotr Jastrzębski"

[Author]
    name = "Piotr J"
    
[params]
  description = "My site with the stuff" # optional
  twitter = "https://twitter.com/evilentity" # optional
  github = "https://github.com/piotr-j/" # optional
  linkedin = "https://www.linkedin.com/profile/view?id=289548369"
  #headerCover = "images/headerCover.png" # optional
  #footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "UA-49968515-1" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" 

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4